server:
  port: 15014
spring:
  application:
    name: ${project.artifactId}
---
# Milvus 配置
milvus:
  host: 175.178.193.128
  port: 20016
  database: default
  username: root
  password: Milvus
---
# Spring AI 配置
spring:
  ai:
    openai:
      base-url: https://api.chatanywhere.tech
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini