server:
  port: 19001
spring:
  application:
    name: ${project.artifactId}
---
# Spring AI 配置
spring:
  ai:
#    openai:
#      base-url: https://free.v36.cm
#      api-key: ${OPENAI_API_KEY}
#      chat:
#        options:
#          model: gpt-4o-mini
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        options:
          model: deepseek-v3.2
